version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    ports:
      - "5000:5000"  # Maps host port 5000 to container port 5000
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:mysecretpassword@db/your_database_name"
      OPENAI_KEY: ${OPENAI_KEY}  # Ensures the OpenAI key is matched with your environment variable
      INIT_DB: "true"  # Add this line to control DB initialization
    networks:
      - backend
    volumes:
      - .:/app
    command: >
      ./entrypoint.sh  # Make sure the entrypoint.sh is executable and starts correctly

networks:
  backend:  # Defines a network named 'backend' for inter-service communication

volumes:
  postgres_data:  # Persists PostgreSQL data
